package com.cheffoafk.voiceassistant.domain

val DEFAULT_SUGGESTION_DICTIONARY = listOf(
    "abbracciami",
    "abbraccio",
    "acqua",
    "adesso",
    "alzarmi",
    "andiamo",
    "ansia",
    "appuntamento",
    "aiuto",
    "ascolto",
    "attesa",
    "bene",
    "bisogno",
    "buongiorno",
    "buonanotte",
    "caldo",
    "camera",
    "camminare",
    "cielo",
    "ciao",
    "cibo",
    "clinica",
    "compagnia",
    "coperta",
    "cuscino",
    "difficile",
    "dolore",
    "dormire",
    "farmaci",
    "famiglia",
    "fame",
    "fisioterapia",
    "freddo",
    "grazie mille",
    "grazie",
    "ho bisogno",
    "idratarmi",
    "infermiere",
    "letto",
    "male",
    "mangiare",
    "medicina",
    "medico",
    "mi aiuti",
    "mi sento",
    "no",
    "non capisco",
    "ok",
    "ospedale",
    "paura",
    "per favore",
    "piacere",
    "posizione",
    "pranzo",
    "ripetere",
    "riposo",
    "sedermi",
    "sedia",
    "sete intensa",
    "sete",
    "stanco",
    "stare meglio",
    "stanza",
    "sto bene",
    "sto male",
    "subito",
    "telefono",
    "toccare",
    "tosse",
    "uscire",
    "va bene",
    "va male",
    "voglio",
    "voglio acqua",
    "voglio mangiare",
    "voglio riposare",
    "vorrei",
    "yes"
)
